FROM codemagic:base

RUN apt-get update \
 && apt-get install -y libssl-dev valgrind

RUN chown hacker:hacker /home/hacker/.bashrc \
 && su - hacker -c "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
