FROM debian:stretch

RUN apt-get update \
 && apt-get install -y unattended-upgrades \
 && unattended-upgrades -d \
 && apt-get install -y \
    bash-completion build-essential curl entr git locales locales-all procps ruby-dev silversearcher-ag sudo tmux vim \
 && gem install travis

ENV EDITOR=/usr/bin/vim

RUN useradd -ms /bin/bash hacker \
 && echo 'hacker ALL=NOPASSWD: ALL' > /etc/sudoers

RUN git config --global --add auto.ui true \
 && git config --global credential.helper 'cache --timeout 86400'

RUN mkdir -p /home/hacker/.vim \
 && git clone --depth 1 --branch v2.4 https://github.com/tpope/vim-pathogen \
    /home/hacker/.vim \
 && mkdir -p /home/hacker/.vim/swp \
 && chown hacker:hacker /home/hacker/.vim/swp \
 && git clone --depth 1 --branch 1.80 https://github.com/ctrlpvim/ctrlp.vim \
    /home/hacker/.vim/bundle/ctrlp.vim \
 && git clone --depth 1 https://github.com/itchyny/lightline.vim \
    /home/hacker/.vim/bundle/lightline.vim \
 && git clone --depth 1 https://github.com/altercation/vim-colors-solarized.git \
    /home/hacker/.vim/bundle/vim-colors-solarized.git \
 && git clone --depth 1 --branch "v3.8.1" https://github.com/sheerun/vim-polyglot \
    /home/hacker/.vim/bundle/vim-polyglot \
 && git clone --depth 1 https://github.com/tpope/vim-sensible \
    /home/hacker/.vim/bundle/vim-sensible \
 && git clone --depth 1 https://github.com/tpope/vim-sleuth.git \
    /home/hacker/.vim/bundle/vim-sleuth \
 && git clone --depth 1 https://github.com/tpope/vim-unimpaired.git \
    /home/hacker/.vim/bundle/vim-unimpaired

RUN git clone --depth 1 https://github.com/riobard/bash-powerline.git \
    /home/hacker/.bash-powerline

RUN git clone --depth 1 https://github.com/gpakosz/.tmux.git \
    /home/hacker/.tmux \
 && ln -s -f .tmux/.tmux.conf /home/hacker/.tmux.conf

COPY dotfiles/ /home/hacker/

RUN mkdir /workspace
WORKDIR /workspace

ENV LC_ALL en_US.UTF-8

CMD tmux
