FROM debian:bullseye

RUN apt-get update \
 && apt-get install -y unattended-upgrades \
 && unattended-upgrades -d \
 && apt-get install -y \
    autoconf bash-completion build-essential curl entr git libncurses-dev locales locales-all pkg-config procps ruby-dev silversearcher-ag sudo tmux

RUN git clone --depth 1 --branch v0.56.0 https://github.com/junegunn/fzf.git /usr/local/src/fzf \
 && /usr/local/src/fzf/install \
 && ln -sf /usr/local/src/fzf/bin/fzf /usr/bin/fzf

RUN git clone --depth 1 --branch v9.0.1443 https://github.com/vim/vim.git /usr/local/src/vim \
 && cd /usr/local/src/vim \
 && ./configure \
 && make \
 && make install

ENV EDITOR=/usr/bin/vim

RUN useradd -ms /bin/bash hacker \
 && echo 'hacker ALL=NOPASSWD: ALL' > /etc/sudoers

RUN git config --global --add auto.ui true \
 && git config --global credential.helper 'cache --timeout 86400'

RUN mkdir -p /home/hacker/.vim \
 && git clone --depth 1 --branch v2.4 https://github.com/tpope/vim-pathogen \
    /home/hacker/.vim \
 && mkdir -p /home/hacker/.vim/swp \
 && chown hacker:hacker /home/hacker/.vim/swp \
 && mkdir -p /home/hacker/.vim/bundle/fzf/plugin \
 && cp /usr/local/src/fzf/plugin/fzf.vim /home/hacker/.vim/bundle/fzf/plugin \
 && git clone --depth 1 https://github.com/github/copilot.vim.git \
    /home/hacker/.vim/bundle/copilot.vim \
 && git clone --depth 1 https://github.com/junegunn/fzf.vim \
    /home/hacker/.vim/bundle/fzf.vim \
 && git clone --depth 1 https://github.com/itchyny/lightline.vim \
    /home/hacker/.vim/bundle/lightline.vim \
 && git clone --depth 1 https://github.com/altercation/vim-colors-solarized.git \
    /home/hacker/.vim/bundle/vim-colors-solarized.git \
 && git clone --depth 1 https://github.com/lstephen/vim-hardtime.git \
    /home/hacker/.vim/bundle/vim-hardtime \
 && git clone --depth 1 --branch "v3.8.1" https://github.com/sheerun/vim-polyglot \
    /home/hacker/.vim/bundle/vim-polyglot \
 && git clone --depth 1 https://github.com/tpope/vim-sensible \
    /home/hacker/.vim/bundle/vim-sensible \
 && git clone --depth 1 https://github.com/tpope/vim-sleuth.git \
    /home/hacker/.vim/bundle/vim-sleuth \
 && git clone --depth 1 https://github.com/tpope/vim-unimpaired.git \
    /home/hacker/.vim/bundle/vim-unimpaired

RUN git clone --depth 1 https://github.com/riobard/bash-powerline.git \
    /home/hacker/.bash-powerline

RUN git clone --depth 1 https://github.com/gpakosz/.tmux.git \
    /home/hacker/.tmux \
 && sed -i '/_apply_plugins$/d' /home/hacker/.tmux/.tmux.conf \
 && ln -s -f /home/hacker/.tmux/.tmux.conf /home/hacker/.tmux.conf

RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - \
 && apt-get install -y nodejs

COPY dotfiles/ /home/hacker/

RUN mkdir /workspace
WORKDIR /workspace

ENV LC_ALL=en_US.UTF-8

CMD ["tmux"]
