FROM debian:bookworm

RUN apt-get update \
 && apt-get install -y unattended-upgrades \
 && unattended-upgrades -d \
 && apt-get install -y \
    autoconf bash-completion build-essential curl git libncurses-dev locales locales-all \
    pkg-config procps sudo tmux jq tree htop ripgrep bat fd-find

RUN git clone --depth 1 --branch v0.56.0 https://github.com/junegunn/fzf.git /usr/local/src/fzf \
 && /usr/local/src/fzf/install \
 && ln -sf /usr/local/src/fzf/bin/fzf /usr/bin/fzf

RUN git clone --depth 1 --branch v9.0.1443 https://github.com/vim/vim.git /usr/local/src/vim \
 && cd /usr/local/src/vim \
 && ./configure \
 && make \
 && make install

ENV EDITOR=/usr/local/bin/vim

RUN useradd -ms /bin/bash hacker \
 && echo 'hacker ALL=NOPASSWD: ALL' > /etc/sudoers.d/hacker \
 && chmod 0440 /etc/sudoers.d/hacker

RUN mkdir -p /home/hacker/.vim \
 && git clone --depth 1 --branch v2.4 https://github.com/tpope/vim-pathogen \
    /home/hacker/.vim \
 && mkdir -p /home/hacker/.vim/swp \
 && mkdir -p /home/hacker/.vim/bundle/fzf/plugin \
 && cp /usr/local/src/fzf/plugin/fzf.vim /home/hacker/.vim/bundle/fzf/plugin \
 && git clone --depth 1 https://github.com/junegunn/fzf.vim \
    /home/hacker/.vim/bundle/fzf.vim \
 && git clone --depth 1 https://github.com/itchyny/lightline.vim \
    /home/hacker/.vim/bundle/lightline.vim \
 && git clone --depth 1 https://github.com/altercation/vim-colors-solarized.git \
    /home/hacker/.vim/bundle/vim-colors-solarized.git \
 && git clone --depth 1 https://github.com/lstephen/vim-hardtime.git \
    /home/hacker/.vim/bundle/vim-hardtime \
 && git clone --depth 1 --branch "v3.8.1" https://github.com/sheerun/vim-polyglot \
    /home/hacker/.vim/bundle/vim-polyglot \
 && git clone --depth 1 https://github.com/tpope/vim-sensible \
    /home/hacker/.vim/bundle/vim-sensible \
 && git clone --depth 1 https://github.com/tpope/vim-sleuth.git \
    /home/hacker/.vim/bundle/vim-sleuth \
 && git clone --depth 1 https://github.com/tpope/vim-unimpaired.git \
    /home/hacker/.vim/bundle/vim-unimpaired \
 && chown -R hacker:hacker /home/hacker/.vim

RUN git clone --depth 1 https://github.com/riobard/bash-powerline.git \
    /home/hacker/.bash-powerline \
 && chown -R hacker:hacker /home/hacker/.bash-powerline

RUN git clone --depth 1 https://github.com/gpakosz/.tmux.git \
    /home/hacker/.tmux \
 && sed -i '/_apply_plugins$/d' /home/hacker/.tmux/.tmux.conf \
 && ln -s -f /home/hacker/.tmux/.tmux.conf /home/hacker/.tmux.conf \
 && chown -R hacker:hacker /home/hacker/.tmux \
 && chown hacker:hacker /home/hacker/.tmux.conf

RUN su - hacker -c "curl -fsSL https://claude.ai/install.sh | bash"

RUN su - hacker -c "git config --global --add auto.ui true \
 && git config --global merge.conflictStyle zdiff3"

COPY dotfiles/ /home/hacker/

RUN chown -R hacker:hacker /home/hacker/.claude /home/hacker/.config \
 && chown hacker:hacker /home/hacker/.bashrc /home/hacker/.vimrc /home/hacker/.emoji-log /home/hacker/.tmux.conf.local /home/hacker/.claude.json

RUN mkdir /workspace
WORKDIR /workspace

ENV LC_ALL=en_US.UTF-8

CMD ["tmux"]
